### PR TITLE
Some Project Fixes

### PR DESCRIPTION
**Pull request by amitjoy**
1. Added Eclipse Workspace Compatible .classpath and .project files for LED Controller Example Project
2. Removed white space in Bnd Descriptor File due to Bundle Build Failure
3. Added Required Google Guava Dependency to Configuration Project (CNF)

Signed-off-by: Amit Kumar Mondal admin@amitinside.com

### CODE REVIEW

**Comment by pkriens** [comment]
Is there a way to skip the Guava dependency? I find that the builtin collections in Java 8 cover almost all needs?

**Comment by amitjoy** [comment]
I have removed the Guava Dependency from the application.

**Comment by pkriens** [comment]
Thanks for the quick reply! Sorry for the delay, I really want to go deeper into your code and feel I am ignoring you too much, please hang  in. 

I would love a separate MQTT bundle. maybe @tverbele would be interested in providing something here because he is working on something for OSGi specifications. It would also be nice if we could get this example as a standalone workspace. I am too busy right now so I merge this. Thanks!

**Comment by amitjoy** [comment]
No problem at all. I am just curious to know about separating MQTT bundle. For the LED Controller Example Application, I have already created separate API and Provider bundles for MQTT Communication. Would you please enlighten on it more?

**Comment by pkriens** [comment]
The current thinking in the OSGi is to go like: https://github.com/osgi/design/blob/master/rfps/rfp-0180-IoT-Protocols-MQTT.pdf (this is an RFP so it should be just requirements). I wonder if we could adapt the example to let the MQTT events flow over Event Admin? 

I also would appreciate it if you could move all the bundles for the LED example to a new workspace (e.g. osgi.enroute.examples.ledovermqtt). Since it consists of a number of related bundles it would be more clear what belongs together? 

I REALLY appreciate what you're doing with this and I am feeling a bit guilty giving you not enough attention but there are currently so many things going on simultaneously :-( And this is really an area I like ...

**Comment by amitjoy** [comment]
It would be great to have such MQTT Bundle which incorporates EventAdmin for MQTT Communication. The currently available libraries are just standalone libraries and hence don't incorporate such Event Mechanisms.

As soon as I get time, I would relocate the LED Controller Application Project in a separate workspace directory.

**Comment by pkriens** [comment]
Great!

**Pull request merged**
