### PR TITLE
LED Controller Example Application

### PR DESCRIPTION
**Pull request by amitjoy**
Added new Example project using OSGi Enroute to control LEDs connected
to Raspberry Pi GPIO Pins in conjunction with MQTT

### CODE REVIEW

**Comment by pkriens** [comment]
Thanks! I like this example a lot!
That said, as an OSGi enRoute example I would like to make some changes to make it more ' OSGi enRoute' like. :-)

This means it needs to use Config Admin for any configuration and services where applicable. In this case, it seems to make more sense that the LedController is actually a service. The receiving of the message should be whiteboard. The actual pins should be configurable by Config Admin + Web Console ( i.e. with metatype). And last the, server URI should be configurable. It would also need some document explaining how to trigger the event (I assume http://iot.eclipse.org/demo/#/devices/%23 ?)

You also have an NPE on line https://github.com/osgi/osgi.enroute.examples/pull/2/files#diff-f3c2273d2414b6c84d2f80afcf13ebceR81 :-)

Shall I clone your branch and propose these changes or do you want to do it yourself?

Again, I really like it that you provide such an example!

**Comment by amitjoy** [comment]
Thanks for your helpful feedback. Basically I thought of making it a simple OSGi bundle, just for the sake of an example but it would be better to provide few more bundles which work more cohesive tasks. I would try to make some more changes to have few more cohesive bundles which showcase the power of OSGi micro-services in context of this example.

**Comment by pkriens** [comment]
Ok! I really appreciate what you're doing so please take any feedback as positive. It is just that I want all OSGi enRoute examples to be "pure" OSGi and using best practices.

Don't go overboard with the bundles. The only split I see is a MQTT white board bundle where the channel is defined by a service property of the service receiving the message. (This could be really useful for OSGi enRoute IoT API 10!)

**Comment by amitjoy** [comment]
I really do appreciate your positive feedback and I will try my best to OSGi-fy this solution using OSGi Enroute micro-services.

**Comment by amitjoy** [comment]
Hi Peter,
Would you please check the current commit for this example application?

Thanks,

**Comment by pkriens** [comment]
I want to take your contribution but because of OSGi we need you to sign off the commits. We prepared the following doc for this: https://github.com/osgi/osgi.enroute.examples/blob/master/CONTRIBUTING.md

After this I accept the PR and then will propose a number of changes. 

Sorry to put some hurdles on your way. I really appreciate what you're doing though!

**Comment by amitjoy** [comment]
Hi Peter,

As you have suggested, I have signed-off all the previous commits and pushed them to the remote repo.

Thanks,

**Comment by amitjoy** [comment]
Due to some major issues in recommitting previous commits with sign-off, I am closing this Pull Request. I will commit the new sources in a new Pull Request.

Thanks,

**Pull request closed without merging**
